export const siteConfig = {
  name: "Rizwan Saeed",
  title: "Digital Marketing Manager, Performance Marketer & Shopify Developer",
  shortBio: "Helping businesses in the UAE, USA, UK and worldwide acquire qualified leads, scale online revenue and build high-converting e-commerce systems.",
  fullBio: "Rizwan Saeed is a Digital Marketing Manager and Shopify Developer specializing in performance marketing, lead generation, e-commerce growth and conversion-focused web development. He has managed campaigns and digital projects for hospitality, retail and B2B brands across the UAE, USA and UK.",
  url: "https://rizwansaddique.site",
  email: "Hello@RizwanSaddique.site",
  phone: "+92 306 4402649",
  whatsappUrl: "https://wa.me/923064402649?text=Hi%20Rizwan,%20I'd%20like%20to%20discuss%20a%20digital%20growth%20project.",
  linkedin: "https://linkedin.com/in/rizwansaeed610",
  facebook: "https://www.facebook.com/RIZWANSAEED610",
  instagram: "https://www.instagram.com/rizwansaeed612",
  youtube: "https://youtube.com/@RizwanSaddique1",
  dribbble: "https://dribbble.com/rizwansaeed",
  tiktok: "https://www.tiktok.com/@rizwansaddique610",
  github: "https://github.com/Rizwansaeed61",
  twitter: "https://twitter.com/rizwansaeed",
  location: "Multan, Pakistan",
  targetMarkets: ["UAE", "USA", "UK", "International"],
  availabilityBadge: "Available for selected international projects",
  verifiedMetrics: {
    revenueGenerated: "AED 4.2M+",
    adSpendManaged: "AED 850K",
    yearsExperience: "5+ Years",
    marketsServed: "UAE · USA · UK",
  },
};
